### ISSUE TITLE
Use Template Haskell?

### ISSUE THREAD

**Issue by FranklinChen** [zudov/html5-entity#1]
Just curious: is there a reason you wrote a separate generator program rather than using Template Haskell?

**Comment by zudov** [comment]
@FranklinChen Indeed there is. If I was using template-haskell, the package would have to depend on `template-haskell` and `aeson`, even though these dependencies wouldn't kill anyone, there is no real need in them. Beside, I don't see a need to use same data for generating same code on every installation instead of just doing it once.

If you are interested I've almost finished a blog post about library, would link it here when it will be published.

Thanks for asking

**Comment by zudov** [comment]
@FranklinChen Here it is http://blog.zudov.me/articles/html5-entity.html

**Comment by FranklinChen** [comment]
Yeah, that's what I thought... avoiding imposing dependencies is often a consideration.

**Comment by zudov** [comment]
Yep. I am generally not against additional heavy dependencies when they make sense.
But that's not the case.
